version: "3.7"
services:
  webapp:
    build: ./app
    ports:
      - 5000:8080
    volumes:
      - ./DB/:/usr/src/app/DB/
    restart:  unless-stopped

  scraper:
    build: ./scraper
    volumes:
      - ./DB/:/DB/
    restart:  unless-stopped

  webserver:
    build: ./apache
    restart:  always
    ports:
    - 80:80
    - 443:443





